version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:oQbVvWs3tHsouVVGIhue/ZQX3p7OuQ8Z4s6oDOhXK7I=
      - DB_CONNECTION: circle_testing
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: src
    steps:
      - checkout
      - run:
          working_directory: src
          command: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
      - run:
          working_directory: src
          name: npm ci
          command: |
              if [ ! -d node_modules ]; then
                npm ci
              fi
      - save_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules
      - run:
          working_directory: src
          name: Run npm
          command: npm run dev
      # - run:
      #     working_directory: src
      #     name: Migration & Seeding
      #     command: php artisan migrate --seed
      - run:
          working_directory: src
          name: php test
          command: vendor/bin/phpunit
