version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          working_directory: src
          command: sudo composer self-update --2
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - run:
          working_directory: src
          command: npm ci
      - run:
          working_directory: src
          command: npm run dev
      - run:
          name: php test
          working_directory: src
          command: vendor/bin/phpunit
