version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/grfl/src

permissions:
  - object: /var/www/grfl/src
    owner: grfl
    group: grfl

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: grfl
